language: python
python: 2.7
addons:
  firefox: 47.0.1
env:
  - TOXENV=tests DISPLAY=:99.0
  - TOXENV=flake8
install:
  - pip install tox
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - tox
notifications:
  email: webqa-ci@mozilla.org
